
/* Drop Tables */

DROP TABLE IF EXISTS PUBLIC.DETALLEVENTA;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CAT_TIPOSUSUARIO;
DROP TABLE IF EXISTS NUMTARJETA;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS PERSONA;
DROP TABLE IF EXISTS PUBLIC.PRODUCTO;



/* Drop Sequences */

DROP SEQUENCE IF EXISTS PUBLIC.DETALLEVENTA_IDDETALLEVENTA_SEQ;
DROP SEQUENCE IF EXISTS PUBLIC.PRODUCTO_IDPRODUCTO_SEQ;
DROP SEQUENCE IF EXISTS PUBLIC.VENTA_IDVENTA_SEQ;




/* Create Sequences */

CREATE SEQUENCE PUBLIC.VENTA_IDVENTA_SEQ INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;



/* Create Tables */

CREATE TABLE CAT_TIPOSUSUARIO
(
	IDTIPOUSUARIO INT NOT NULL,
	DESCRIPCION VARCHAR,
	PRIMARY KEY (IDTIPOUSUARIO)
) WITHOUT OIDS;


CREATE TABLE NUMTARJETA
(
	NOTARJETA VARCHAR(18) NOT NULL,
	IDCLIENTE INT NOT NULL,
	CODIGOSEGURIDAD INT,
	FECHACADUCIDAD DATE,
	PRIMARY KEY (NOTARJETA)
) WITHOUT OIDS;


CREATE TABLE PEDIDO
(
	IDPEDIDO SERIAL NOT NULL,
	IDPRODUCTO INT NOT NULL,
	FECHAPEDIDO DATE,
	CANTIDAD INT,
	PRIMARY KEY (IDPEDIDO)
) WITHOUT OIDS;


CREATE TABLE PERSONA
(
	IDCLIENTE SERIAL NOT NULL,
	NOMBRE VARCHAR,
	APPAT VARCHAR,
	APMAT VARCHAR,
	FECHNAC DATE,
	TELEFONO VARCHAR,
	DIRECCION VARCHAR,
	CELULAR VARCHAR,
	EMAIL VARCHAR,
	PRIMARY KEY (IDCLIENTE)
) WITHOUT OIDS;


ALTER SEQUENCE PERSONA_IDCLIENTE_SEQ INCREMENT 1 MINVALUE 0 MAXVALUE 10000;


CREATE TABLE USUARIO
(
	IDUSUARIO SERIAL NOT NULL,
	TIPOUSUARIO INT,
	IDCLIENTE INT,
	LOGIN VARCHAR NOT NULL,
	PASSWORD VARCHAR NOT NULL,
	FECHACREACION DATE,
	PRIMARY KEY (IDUSUARIO)
) WITHOUT OIDS;


CREATE TABLE PUBLIC.DETALLEVENTA
(
	IDDETALLEVENTA SERIAL NOT NULL,
	IDPRODUCTO INT NOT NULL,
	IDUSUARIO INT NOT NULL,
	CANTIDAD SMALLINT,
	HORA TIME,
	FECHADETALLEVENTA DATE,
	CONSTRAINT detalleventa_pkey PRIMARY KEY (IDDETALLEVENTA)
) WITHOUT OIDS;


CREATE TABLE PUBLIC.PRODUCTO
(
	IDPRODUCTO SERIAL NOT NULL,
	PRODUCTO VARCHAR(50),
	CANTIDAD SMALLINT,
	PRECIO FLOAT,
	RUTA VARCHAR UNIQUE,
	CONSTRAINT producto_pkey PRIMARY KEY (IDPRODUCTO)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE USUARIO
	ADD FOREIGN KEY (TIPOUSUARIO)
	REFERENCES CAT_TIPOSUSUARIO (IDTIPOUSUARIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE NUMTARJETA
	ADD FOREIGN KEY (IDCLIENTE)
	REFERENCES PERSONA (IDCLIENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (IDCLIENTE)
	REFERENCES PERSONA (IDCLIENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PUBLIC.DETALLEVENTA
	ADD FOREIGN KEY (IDUSUARIO)
	REFERENCES USUARIO (IDUSUARIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PEDIDO
	ADD FOREIGN KEY (IDPRODUCTO)
	REFERENCES PUBLIC.PRODUCTO (IDPRODUCTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PUBLIC.DETALLEVENTA
	ADD CONSTRAINT DETALLEVENTA_IDPRODUCTO_FKEY FOREIGN KEY (IDPRODUCTO)
	REFERENCES PUBLIC.PRODUCTO (IDPRODUCTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



